<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>    

<!DOCTYPE html>
<html>

	<head>
		<meta charset="ISO-8859-1">
		<title>add customer</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	</head>

	<body>											<!-- mapping to validateForm in customer controller -->
			<div class="container">
				<form:form modelAttribute="customer" action="validateForm">
					
					<!-- need to add customerId to customer object -->
					<!-- it is null when we add customer because it is auto-generated by DB-->
					<!-- & available when we update customer -->
					<form:hidden path="id"/>
					
					<div class="form-group">
						First name(*)<form:input path="f_name" />
						<form:errors path="f_name"/>	<!-- for this add hibernate validation jar -->
						<br><br>
										
						Last name(*)<form:input path="l_name"/>
						<form:errors path="l_name"/>
						<br><br>
						
						
						email(*)<form:input path="email"/>
						<form:errors path="email"/>
						<br><br>
					</div>
					
					<input type="submit" value="submit"> 
					
				</form:form>
				
				<a href="${pageContext.request.contextPath}/customer/list">Back to List</a>
				
			</div>
	</body>
</html>